import { Scholarship, Testimonial, TeamMember } from '@/types/scholarship';

export const scholarships: Scholarship[] = [
  {
    id: '1',
    title: 'Chevening Scholarship',
    titleAr: 'منحة تشيفنينج',
    slug: 'chevening-scholarship',
    university: 'Various UK Universities',
    universityAr: 'جامعات بريطانية متعددة',
    country: 'United Kingdom',
    countryCode: 'uk',
    countryAr: 'المملكة المتحدة',
    deadline: '2025-11-05',
    fundingType: 'fully-funded',
    level: 'master',
    field: 'business',
    description: 'Chevening Scholarships are the UK government\'s global scholarship programme, funded by the Foreign, Commonwealth and Development Office (FCDO) and partner organisations. The scholarships are awarded to individuals with demonstrable leadership potential who also have strong academic backgrounds.',
    descriptionAr: 'منح تشيفنينج هي برنامج المنح الدراسية العالمي للحكومة البريطانية، والممول من مكتب الخارجية والكومنولث والتنمية والمنظمات الشريكة. تُمنح المنح للأفراد الذين يتمتعون بإمكانيات قيادية واضحة ولديهم خلفيات أكاديمية قوية.',
    eligibility: [
      'Be a citizen of a Chevening-eligible country',
      'Return to your country for a minimum of two years after your award',
      'Have an undergraduate degree',
      'Have at least two years of work experience',
    ],
    eligibilityAr: [
      'أن تكون مواطناً في دولة مؤهلة لمنحة تشيفنينج',
      'العودة إلى بلدك لمدة سنتين على الأقل بعد انتهاء المنحة',
      'الحصول على شهادة البكالوريوس',
      'امتلاك خبرة عملية لا تقل عن سنتين',
    ],
    benefits: [
      'Full tuition fees',
      'Monthly living allowance',
      'Return economy flights',
      'Arrival and departure allowances',
      'Thesis or dissertation grant',
    ],
    benefitsAr: [
      'الرسوم الدراسية الكاملة',
      'بدل معيشة شهري',
      'تذاكر سفر ذهاب وإياب بالدرجة الاقتصادية',
      'بدل وصول ومغادرة',
      'منحة للرسالة أو الأطروحة',
    ],
    requirements: [
      'Academic transcripts',
      'Two reference letters',
      'Personal statement',
      'Valid passport',
    ],
    requirementsAr: [
      'كشف الدرجات الأكاديمية',
      'خطابان توصية',
      'بيان شخصي',
      'جواز سفر ساري المفعول',
    ],
    howToApply: 'Apply online through the official Chevening website during the application period. Complete your application with all required documents and submit before the deadline.',
    howToApplyAr: 'قدم طلبك عبر الإنترنت من خلال موقع تشيفنينج الرسمي خلال فترة التقديم. أكمل طلبك مع جميع المستندات المطلوبة وأرسله قبل الموعد النهائي.',
    applicationUrl: 'https://www.chevening.org/scholarships/',
    image: 'https://images.unsplash.com/photo-1526129318478-62ed807ebdf9?w=800&q=80',
    duration: '1 year',
    durationAr: 'سنة واحدة',
    isFeatured: true,
    isNew: false,
    createdAt: '2024-01-15',
  },
  {
    id: '2',
    title: 'DAAD Scholarship',
    titleAr: 'منحة DAAD الألمانية',
    slug: 'daad-scholarship',
    university: 'German Universities',
    universityAr: 'الجامعات الألمانية',
    country: 'Germany',
    countryCode: 'germany',
    countryAr: 'ألمانيا',
    deadline: '2025-10-15',
    fundingType: 'fully-funded',
    level: 'master',
    field: 'engineering',
    description: 'The German Academic Exchange Service (DAAD) offers scholarships for international students to study in Germany. The program supports talented students in their pursuit of academic excellence at German universities.',
    descriptionAr: 'تقدم الهيئة الألمانية للتبادل الأكاديمي (DAAD) منحاً دراسية للطلاب الدوليين للدراسة في ألمانيا. يدعم البرنامج الطلاب الموهوبين في سعيهم لتحقيق التميز الأكاديمي في الجامعات الألمانية.',
    eligibility: [
      'Bachelor\'s degree in a relevant field',
      'Two years of professional experience',
      'Strong academic record',
      'Language proficiency (German or English)',
    ],
    eligibilityAr: [
      'شهادة بكالوريوس في مجال ذي صلة',
      'سنتان من الخبرة المهنية',
      'سجل أكاديمي قوي',
      'إتقان اللغة (الألمانية أو الإنجليزية)',
    ],
    benefits: [
      'Monthly scholarship payment of €934',
      'Travel allowance',
      'Health insurance subsidy',
      'Study and research allowance',
    ],
    benefitsAr: [
      'مبلغ شهري 934 يورو',
      'بدل سفر',
      'دعم التأمين الصحي',
      'بدل الدراسة والبحث',
    ],
    requirements: [
      'Online application form',
      'CV in tabular form',
      'Letter of motivation',
      'Academic certificates',
    ],
    requirementsAr: [
      'نموذج طلب إلكتروني',
      'سيرة ذاتية في شكل جدول',
      'خطاب تحفيزي',
      'الشهادات الأكاديمية',
    ],
    howToApply: 'Submit your application through the DAAD portal. Applications must include all required documents.',
    howToApplyAr: 'أرسل طلبك عبر بوابة DAAD. يجب أن تتضمن الطلبات جميع المستندات المطلوبة.',
    applicationUrl: 'https://www.daad.de/en/',
    image: 'https://images.unsplash.com/photo-1467269204594-9661b134dd2b?w=800&q=80',
    duration: '2 years',
    durationAr: 'سنتان',
    isFeatured: true,
    isNew: true,
    createdAt: '2024-02-01',
  },
  {
    id: '3',
    title: 'Fulbright Foreign Student Program',
    titleAr: 'برنامج فولبرايت للطلاب الأجانب',
    slug: 'fulbright-scholarship',
    university: 'US Universities',
    universityAr: 'الجامعات الأمريكية',
    country: 'United States',
    countryCode: 'usa',
    countryAr: 'الولايات المتحدة',
    deadline: '2025-06-01',
    fundingType: 'fully-funded',
    level: 'master',
    field: 'science',
    description: 'The Fulbright Program is the U.S. government\'s flagship international educational exchange program. It provides funding for students, scholars, teachers, and professionals to study, research, or teach abroad.',
    descriptionAr: 'برنامج فولبرايت هو البرنامج الرائد للتبادل التعليمي الدولي للحكومة الأمريكية. يوفر تمويلاً للطلاب والباحثين والمعلمين والمهنيين للدراسة أو البحث أو التدريس في الخارج.',
    eligibility: [
      'Bachelor\'s degree or equivalent',
      'Proficiency in English',
      'Strong academic record',
      'Leadership potential',
    ],
    eligibilityAr: [
      'شهادة بكالوريوس أو ما يعادلها',
      'إتقان اللغة الإنجليزية',
      'سجل أكاديمي قوي',
      'إمكانيات قيادية',
    ],
    benefits: [
      'Full tuition coverage',
      'Living stipend',
      'Round-trip airfare',
      'Health insurance',
      'Book and equipment allowances',
    ],
    benefitsAr: [
      'تغطية الرسوم الدراسية الكاملة',
      'راتب معيشة',
      'تذاكر سفر ذهاب وإياب',
      'تأمين صحي',
      'بدل الكتب والمعدات',
    ],
    requirements: [
      'Academic transcripts',
      'Three letters of recommendation',
      'Personal statement',
      'Study objective statement',
    ],
    requirementsAr: [
      'كشف الدرجات الأكاديمية',
      'ثلاثة خطابات توصية',
      'بيان شخصي',
      'بيان الهدف الدراسي',
    ],
    howToApply: 'Apply through the Fulbright Commission in your home country or through the Institute of International Education (IIE).',
    howToApplyAr: 'قدم طلبك من خلال لجنة فولبرايت في بلدك أو من خلال معهد التعليم الدولي (IIE).',
    applicationUrl: 'https://foreign.fulbrightonline.org/',
    image: 'https://images.unsplash.com/photo-1485738422979-f5c462d49f74?w=800&q=80',
    duration: '1-2 years',
    durationAr: '1-2 سنة',
    isFeatured: true,
    isNew: false,
    createdAt: '2024-01-20',
  },
  {
    id: '4',
    title: 'Australia Awards Scholarships',
    titleAr: 'منح أستراليا',
    slug: 'australia-awards',
    university: 'Australian Universities',
    universityAr: 'الجامعات الأسترالية',
    country: 'Australia',
    countryCode: 'australia',
    countryAr: 'أستراليا',
    deadline: '2025-04-30',
    fundingType: 'fully-funded',
    level: 'master',
    field: 'education',
    description: 'Australia Awards Scholarships are long-term development awards funded by the Australian Government. They aim to contribute to the development needs of Australia\'s partner countries.',
    descriptionAr: 'منح أستراليا هي منح تنموية طويلة الأجل ممولة من الحكومة الأسترالية. تهدف إلى المساهمة في احتياجات التنمية في البلدان الشريكة لأستراليا.',
    eligibility: [
      'Citizen of a participating country',
      'Not hold Australian citizenship',
      'Minimum two years post-study residence',
      'Bachelor\'s degree for Master\'s application',
    ],
    eligibilityAr: [
      'أن تكون مواطناً في دولة مشاركة',
      'عدم حمل الجنسية الأسترالية',
      'إقامة سنتين بعد الدراسة كحد أدنى',
      'شهادة بكالوريوس للتقديم على الماجستير',
    ],
    benefits: [
      'Full tuition fees',
      'Return air travel',
      'Establishment allowance',
      'Contribution to living expenses',
      'Overseas student health cover',
    ],
    benefitsAr: [
      'الرسوم الدراسية الكاملة',
      'تذاكر سفر ذهاب وإياب',
      'بدل استقرار',
      'مساهمة في نفقات المعيشة',
      'تغطية صحية للطلاب الدوليين',
    ],
    requirements: [
      'Academic qualifications',
      'IELTS score minimum 6.5',
      'Statement of purpose',
      'Referee reports',
    ],
    requirementsAr: [
      'المؤهلات الأكاديمية',
      'درجة IELTS لا تقل عن 6.5',
      'بيان الغرض',
      'تقارير المرجعين',
    ],
    howToApply: 'Apply through the Australia Awards website during the application round for your country.',
    howToApplyAr: 'قدم طلبك عبر موقع منح أستراليا خلال جولة التقديم لبلدك.',
    applicationUrl: 'https://www.dfat.gov.au/people-to-people/australia-awards',
    image: 'https://images.unsplash.com/photo-1523482580672-f109ba8cb9be?w=800&q=80',
    duration: '1-2 years',
    durationAr: '1-2 سنة',
    isFeatured: false,
    isNew: true,
    createdAt: '2024-02-10',
  },
  {
    id: '5',
    title: 'Erasmus Mundus Joint Masters',
    titleAr: 'إيراسموس موندوس للماجستير المشترك',
    slug: 'erasmus-mundus',
    university: 'European Universities',
    universityAr: 'الجامعات الأوروبية',
    country: 'Netherlands',
    countryCode: 'netherlands',
    countryAr: 'هولندا',
    deadline: '2025-01-15',
    fundingType: 'fully-funded',
    level: 'master',
    field: 'technology',
    description: 'Erasmus Mundus Joint Master Degrees are high-level integrated study programmes at Master level. They are designed and delivered by partnerships of higher education institutions from different countries.',
    descriptionAr: 'درجات الماجستير المشتركة إيراسموس موندوس هي برامج دراسية متكاملة عالية المستوى على مستوى الماجستير. يتم تصميمها وتقديمها من قبل شراكات مؤسسات التعليم العالي من دول مختلفة.',
    eligibility: [
      'Bachelor\'s degree or equivalent',
      'Meet specific program requirements',
      'Language proficiency',
      'Strong academic background',
    ],
    eligibilityAr: [
      'شهادة بكالوريوس أو ما يعادلها',
      'استيفاء متطلبات البرنامج المحددة',
      'إتقان اللغة',
      'خلفية أكاديمية قوية',
    ],
    benefits: [
      'Full tuition coverage',
      'Travel costs',
      'Installation costs',
      'Monthly subsistence allowance',
    ],
    benefitsAr: [
      'تغطية الرسوم الدراسية الكاملة',
      'تكاليف السفر',
      'تكاليف الاستقرار',
      'بدل إعاشة شهري',
    ],
    requirements: [
      'Degree certificates',
      'Transcripts',
      'CV/Resume',
      'Motivation letter',
      'Language certificates',
    ],
    requirementsAr: [
      'شهادات الدرجة',
      'كشف الدرجات',
      'السيرة الذاتية',
      'خطاب التحفيز',
      'شهادات اللغة',
    ],
    howToApply: 'Apply directly to the consortium managing the EMJMD you wish to apply for through their application portal.',
    howToApplyAr: 'قدم طلبك مباشرة إلى الاتحاد الذي يدير برنامج EMJMD الذي ترغب في التقديم له من خلال بوابة التقديم الخاصة بهم.',
    applicationUrl: 'https://erasmus-plus.ec.europa.eu/',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    duration: '2 years',
    durationAr: 'سنتان',
    isFeatured: true,
    isNew: false,
    createdAt: '2024-01-10',
  },
  {
    id: '6',
    title: 'Gates Cambridge Scholarship',
    titleAr: 'منحة جيتس كامبريدج',
    slug: 'gates-cambridge',
    university: 'University of Cambridge',
    universityAr: 'جامعة كامبريدج',
    country: 'United Kingdom',
    countryCode: 'uk',
    countryAr: 'المملكة المتحدة',
    deadline: '2025-12-03',
    fundingType: 'fully-funded',
    level: 'phd',
    field: 'science',
    description: 'The Gates Cambridge Scholarship programme was established in October 2000 by a donation of US$210m from the Bill and Melinda Gates Foundation. It is one of the most prestigious scholarships worldwide.',
    descriptionAr: 'تأسس برنامج منحة جيتس كامبريدج في أكتوبر 2000 بتبرع قدره 210 مليون دولار أمريكي من مؤسسة بيل وميليندا جيتس. وهي واحدة من أكثر المنح الدراسية المرموقة في العالم.',
    eligibility: [
      'Outstanding intellectual ability',
      'Leadership potential',
      'Commitment to improving others\' lives',
      'Applying for full-time postgraduate degree',
    ],
    eligibilityAr: [
      'قدرة فكرية متميزة',
      'إمكانيات قيادية',
      'الالتزام بتحسين حياة الآخرين',
      'التقديم لدرجة دراسات عليا بدوام كامل',
    ],
    benefits: [
      'Full cost of studying at Cambridge',
      'Maintenance allowance',
      'Airfare to and from Cambridge',
      'Visa costs and immigration health surcharge',
    ],
    benefitsAr: [
      'التكلفة الكاملة للدراسة في كامبريدج',
      'بدل إعاشة',
      'تذاكر سفر من وإلى كامبريدج',
      'رسوم التأشيرة والرسوم الصحية للهجرة',
    ],
    requirements: [
      'Cambridge application',
      'Gates Cambridge application',
      'Reference letters',
      'Research proposal (for PhD)',
    ],
    requirementsAr: [
      'طلب كامبريدج',
      'طلب جيتس كامبريدج',
      'خطابات التوصية',
      'مقترح البحث (للدكتوراه)',
    ],
    howToApply: 'Apply simultaneously to Cambridge and Gates Cambridge through the university application portal.',
    howToApplyAr: 'قدم طلبك في وقت واحد إلى كامبريدج وجيتس كامبريدج من خلال بوابة التقديم بالجامعة.',
    applicationUrl: 'https://www.gatescambridge.org/',
    image: 'https://images.unsplash.com/photo-1580537659466-0a9bfa916a54?w=800&q=80',
    duration: '3-4 years',
    durationAr: '3-4 سنوات',
    isFeatured: true,
    isNew: false,
    createdAt: '2024-01-05',
  },
  {
    id: '7',
    title: 'MEXT Japanese Government Scholarship',
    titleAr: 'منحة الحكومة اليابانية MEXT',
    slug: 'mext-scholarship',
    university: 'Japanese Universities',
    universityAr: 'الجامعات اليابانية',
    country: 'Japan',
    countryCode: 'japan',
    countryAr: 'اليابان',
    deadline: '2025-05-15',
    fundingType: 'fully-funded',
    level: 'bachelor',
    field: 'technology',
    description: 'The Japanese Government (MEXT) Scholarship provides opportunities to study at Japanese universities. It covers research students, undergraduate students, and teacher training programs.',
    descriptionAr: 'توفر منحة الحكومة اليابانية (MEXT) فرصاً للدراسة في الجامعات اليابانية. تغطي طلاب البحث وطلاب البكالوريوس وبرامج تدريب المعلمين.',
    eligibility: [
      'Age between 17-24 for undergraduates',
      'Completed 12 years of schooling',
      'Willingness to learn Japanese',
      'Good health',
    ],
    eligibilityAr: [
      'العمر بين 17-24 للبكالوريوس',
      'إكمال 12 سنة من التعليم',
      'الرغبة في تعلم اللغة اليابانية',
      'صحة جيدة',
    ],
    benefits: [
      'Tuition fees exemption',
      'Monthly allowance of ¥117,000',
      'Round-trip airfare',
      'Free Japanese language training',
    ],
    benefitsAr: [
      'إعفاء من الرسوم الدراسية',
      'بدل شهري 117,000 ين',
      'تذاكر سفر ذهاب وإياب',
      'تدريب مجاني على اللغة اليابانية',
    ],
    requirements: [
      'Application form',
      'Academic transcripts',
      'Certificate of health',
      'Recommendation letter',
    ],
    requirementsAr: [
      'نموذج الطلب',
      'كشف الدرجات الأكاديمية',
      'شهادة صحية',
      'خطاب توصية',
    ],
    howToApply: 'Apply through the Japanese Embassy or Consulate in your country during the application period.',
    howToApplyAr: 'قدم طلبك من خلال السفارة أو القنصلية اليابانية في بلدك خلال فترة التقديم.',
    applicationUrl: 'https://www.mext.go.jp/en/',
    image: 'https://images.unsplash.com/photo-1480796927426-f609979314bd?w=800&q=80',
    duration: '5 years',
    durationAr: '5 سنوات',
    isFeatured: false,
    isNew: true,
    createdAt: '2024-02-15',
  },
  {
    id: '8',
    title: 'Swiss Government Excellence Scholarships',
    titleAr: 'منح التميز السويسرية الحكومية',
    slug: 'swiss-excellence',
    university: 'Swiss Universities',
    universityAr: 'الجامعات السويسرية',
    country: 'Germany',
    countryCode: 'germany',
    countryAr: 'سويسرا',
    deadline: '2025-08-01',
    fundingType: 'fully-funded',
    level: 'phd',
    field: 'science',
    description: 'The Swiss Government Excellence Scholarships provide highly qualified researchers with the opportunity to pursue doctoral or postdoctoral research at one of the Swiss public universities.',
    descriptionAr: 'توفر منح التميز الحكومية السويسرية للباحثين المؤهلين تأهيلاً عالياً فرصة متابعة البحث الدكتوراه أو ما بعد الدكتوراه في إحدى الجامعات السويسرية العامة.',
    eligibility: [
      'Master\'s degree for PhD applications',
      'PhD for postdoctoral applications',
      'Born after a specific date',
      'Strong academic record',
    ],
    eligibilityAr: [
      'درجة الماجستير لطلبات الدكتوراه',
      'درجة الدكتوراه لطلبات ما بعد الدكتوراه',
      'أن تكون مولوداً بعد تاريخ محدد',
      'سجل أكاديمي قوي',
    ],
    benefits: [
      'Monthly scholarship of CHF 1,920',
      'Tuition fee exemption',
      'Health insurance',
      'Housing allowance',
    ],
    benefitsAr: [
      'منحة شهرية 1,920 فرنك سويسري',
      'إعفاء من الرسوم الدراسية',
      'تأمين صحي',
      'بدل سكن',
    ],
    requirements: [
      'Research proposal',
      'Acceptance from Swiss professor',
      'Academic certificates',
      'Language certificates',
    ],
    requirementsAr: [
      'مقترح بحثي',
      'قبول من أستاذ سويسري',
      'الشهادات الأكاديمية',
      'شهادات اللغة',
    ],
    howToApply: 'Contact the Swiss Embassy in your country and apply through the official channels.',
    howToApplyAr: 'تواصل مع السفارة السويسرية في بلدك وقدم طلبك من خلال القنوات الرسمية.',
    applicationUrl: 'https://www.sbfi.admin.ch/sbfi/en/home.html',
    image: 'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?w=800&q=80',
    duration: '3 years',
    durationAr: '3 سنوات',
    isFeatured: false,
    isNew: false,
    createdAt: '2024-01-25',
  },
];

export const testimonials: Testimonial[] = [
  {
    id: '1',
    name: 'Ahmed Hassan',
    nameAr: 'أحمد حسن',
    university: 'Oxford University',
    universityAr: 'جامعة أكسفورد',
    country: 'UK',
    countryAr: 'بريطانيا',
    quote: 'This platform helped me find the perfect scholarship. The guidance was invaluable in my application journey.',
    quoteAr: 'ساعدتني هذه المنصة في العثور على المنحة المثالية. كان التوجيه لا يقدر بثمن في رحلة تقديمي.',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&q=80',
    scholarshipYear: 2023,
  },
  {
    id: '2',
    name: 'Sara Ali',
    nameAr: 'سارة علي',
    university: 'MIT',
    universityAr: 'معهد ماساتشوستس للتكنولوجيا',
    country: 'USA',
    countryAr: 'أمريكا',
    quote: 'I never thought studying abroad was possible until I discovered the scholarships listed here. Now I\'m living my dream!',
    quoteAr: 'لم أكن أظن أن الدراسة في الخارج ممكنة حتى اكتشفت المنح المدرجة هنا. الآن أعيش حلمي!',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&q=80',
    scholarshipYear: 2024,
  },
  {
    id: '3',
    name: 'Mohammed Khalid',
    nameAr: 'محمد خالد',
    university: 'TU Munich',
    universityAr: 'جامعة ميونيخ التقنية',
    country: 'Germany',
    countryAr: 'ألمانيا',
    quote: 'The detailed information about each scholarship made the application process so much easier. Highly recommended!',
    quoteAr: 'المعلومات المفصلة عن كل منحة جعلت عملية التقديم أسهل بكثير. أنصح به بشدة!',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&q=80',
    scholarshipYear: 2023,
  },
];

export const teamMembers: TeamMember[] = [
  {
    id: '1',
    name: 'Osman Osama Ahmed Ibrahim',
    nameAr: 'عثمان أسامة أحمد إبراهيم',
    role: 'Founder & Developer - MSc Geomatics Engineering',
    roleAr: 'المؤسس والمطور - ماجستير هندسة الجيوماتكس',
    bio: 'MSc in Geomatics Engineering from Karadeniz Technical University, Trabzon, Türkiye (2022-2024). Passionate about helping Sudanese students access international scholarships.',
    bioAr: 'ماجستير في هندسة الجيوماتكس من جامعة كارادينيز التقنية، طرابزون، تركيا (2022-2024). شغوف بمساعدة الطلاب السودانيين في الوصول إلى المنح الدراسية الدولية.',
    avatar: 'https://i.imgur.com/293Vf8j.jpg',
    linkedin: 'https://www.linkedin.com/in/osman-o-a-ibrahim-a02a9a197',
    twitter: 'https://x.com/Osman_Ibrahim93',
  },
  {
    id: '2',
    name: 'Ahmed Abdelbasit',
    nameAr: 'احمد عبدالباسط',
    role: 'YTB Scholar - BSc Civil Engineering Final Year',
    roleAr: 'منحة YTB - بكالوريوس هندسة مدنية سنة نهائية',
    bio: 'Karadeniz Technical University, BSc Civil Engineering final year student. Erasmus+ exchange student at UPT Romania.',
    bioAr: 'جامعة كارادينيز التقنية، طالب سنة نهائية بكالوريوس هندسة مدنية. طالب تبادل إيراسموس+ في جامعة UPT رومانيا.',
    avatar: 'https://imgur.com/QlRDU5F.jpg',
    linkedin: '#',
    twitter: '#',
  },
  {
    id: '3',
    name: 'Esraa Mohammed',
    nameAr: 'إسراء محمد',
    role: 'Graphic Design Diploma – Final Year',
    roleAr: 'دبلوم تصميم جرافيك - سنة نهائية',
    bio: 'Karadeniz Technical University, Final-year Diploma student specializing in Graphic Design, with a strong passion for visual design, digital creativity, and photography.',
    bioAr: 'جامعة كارادينيز التقنية، طالبة سنة نهائية دبلوم تصميم جرافيك، شغوفة بالتصميم البصري والإبداع الرقمي والتصوير الفوتوغرافي.',
    avatar: 'https://imgur.com/rwI0CF0.jpg',
    linkedin: '#',
    twitter: '#',
  },
];

export const categories = [
  { id: 'engineering', icon: 'Wrench', count: 125 },
  { id: 'medicine', icon: 'Stethoscope', count: 89 },
  { id: 'business', icon: 'Briefcase', count: 156 },
  { id: 'arts', icon: 'Palette', count: 67 },
  { id: 'science', icon: 'Atom', count: 142 },
  { id: 'law', icon: 'Scale', count: 45 },
  { id: 'education', icon: 'GraduationCap', count: 78 },
  { id: 'technology', icon: 'Laptop', count: 198 },
];

export const stats = [
  { value: '500+', labelKey: 'scholarships' },
  { value: '200+', labelKey: 'universities' },
  { value: '50+', labelKey: 'countries' },
  { value: '10,000+', labelKey: 'students' },
];
