// All world countries with ISO codes, English names, Arabic names, and flags
// Sorted alphabetically by English name

export interface Country {
  code: string;
  name: string;
  nameAr: string;
  flag: string;
}

export const COUNTRIES: Country[] = [
  { code: 'af', name: 'Afghanistan', nameAr: 'أفغانستان', flag: '🇦🇫' },
  { code: 'al', name: 'Albania', nameAr: 'ألبانيا', flag: '🇦🇱' },
  { code: 'dz', name: 'Algeria', nameAr: 'الجزائر', flag: '🇩🇿' },
  { code: 'ad', name: 'Andorra', nameAr: 'أندورا', flag: '🇦🇩' },
  { code: 'ao', name: 'Angola', nameAr: 'أنغولا', flag: '🇦🇴' },
  { code: 'ag', name: 'Antigua and Barbuda', nameAr: 'أنتيغوا وباربودا', flag: '🇦🇬' },
  { code: 'ar', name: 'Argentina', nameAr: 'الأرجنتين', flag: '🇦🇷' },
  { code: 'am', name: 'Armenia', nameAr: 'أرمينيا', flag: '🇦🇲' },
  { code: 'au', name: 'Australia', nameAr: 'أستراليا', flag: '🇦🇺' },
  { code: 'at', name: 'Austria', nameAr: 'النمسا', flag: '🇦🇹' },
  { code: 'az', name: 'Azerbaijan', nameAr: 'أذربيجان', flag: '🇦🇿' },
  { code: 'bs', name: 'Bahamas', nameAr: 'باهاماس', flag: '🇧🇸' },
  { code: 'bh', name: 'Bahrain', nameAr: 'البحرين', flag: '🇧🇭' },
  { code: 'bd', name: 'Bangladesh', nameAr: 'بنغلاديش', flag: '🇧🇩' },
  { code: 'bb', name: 'Barbados', nameAr: 'باربادوس', flag: '🇧🇧' },
  { code: 'by', name: 'Belarus', nameAr: 'بيلاروسيا', flag: '🇧🇾' },
  { code: 'be', name: 'Belgium', nameAr: 'بلجيكا', flag: '🇧🇪' },
  { code: 'bz', name: 'Belize', nameAr: 'بليز', flag: '🇧🇿' },
  { code: 'bj', name: 'Benin', nameAr: 'بنين', flag: '🇧🇯' },
  { code: 'bt', name: 'Bhutan', nameAr: 'بوتان', flag: '🇧🇹' },
  { code: 'bo', name: 'Bolivia', nameAr: 'بوليفيا', flag: '🇧🇴' },
  { code: 'ba', name: 'Bosnia and Herzegovina', nameAr: 'البوسنة والهرسك', flag: '🇧🇦' },
  { code: 'bw', name: 'Botswana', nameAr: 'بوتسوانا', flag: '🇧🇼' },
  { code: 'br', name: 'Brazil', nameAr: 'البرازيل', flag: '🇧🇷' },
  { code: 'bn', name: 'Brunei', nameAr: 'بروناي', flag: '🇧🇳' },
  { code: 'bg', name: 'Bulgaria', nameAr: 'بلغاريا', flag: '🇧🇬' },
  { code: 'bf', name: 'Burkina Faso', nameAr: 'بوركينا فاسو', flag: '🇧🇫' },
  { code: 'bi', name: 'Burundi', nameAr: 'بوروندي', flag: '🇧🇮' },
  { code: 'cv', name: 'Cabo Verde', nameAr: 'الرأس الأخضر', flag: '🇨🇻' },
  { code: 'kh', name: 'Cambodia', nameAr: 'كمبوديا', flag: '🇰🇭' },
  { code: 'cm', name: 'Cameroon', nameAr: 'الكاميرون', flag: '🇨🇲' },
  { code: 'ca', name: 'Canada', nameAr: 'كندا', flag: '🇨🇦' },
  { code: 'cf', name: 'Central African Republic', nameAr: 'جمهورية أفريقيا الوسطى', flag: '🇨🇫' },
  { code: 'td', name: 'Chad', nameAr: 'تشاد', flag: '🇹🇩' },
  { code: 'cl', name: 'Chile', nameAr: 'تشيلي', flag: '🇨🇱' },
  { code: 'cn', name: 'China', nameAr: 'الصين', flag: '🇨🇳' },
  { code: 'co', name: 'Colombia', nameAr: 'كولومبيا', flag: '🇨🇴' },
  { code: 'km', name: 'Comoros', nameAr: 'جزر القمر', flag: '🇰🇲' },
  { code: 'cg', name: 'Congo', nameAr: 'الكونغو', flag: '🇨🇬' },
  { code: 'cd', name: 'Congo (DRC)', nameAr: 'جمهورية الكونغو الديمقراطية', flag: '🇨🇩' },
  { code: 'cr', name: 'Costa Rica', nameAr: 'كوستاريكا', flag: '🇨🇷' },
  { code: 'hr', name: 'Croatia', nameAr: 'كرواتيا', flag: '🇭🇷' },
  { code: 'cu', name: 'Cuba', nameAr: 'كوبا', flag: '🇨🇺' },
  { code: 'cy', name: 'Cyprus', nameAr: 'قبرص', flag: '🇨🇾' },
  { code: 'cz', name: 'Czech Republic', nameAr: 'جمهورية التشيك', flag: '🇨🇿' },
  { code: 'dk', name: 'Denmark', nameAr: 'الدنمارك', flag: '🇩🇰' },
  { code: 'dj', name: 'Djibouti', nameAr: 'جيبوتي', flag: '🇩🇯' },
  { code: 'dm', name: 'Dominica', nameAr: 'دومينيكا', flag: '🇩🇲' },
  { code: 'do', name: 'Dominican Republic', nameAr: 'جمهورية الدومينيكان', flag: '🇩🇴' },
  { code: 'ec', name: 'Ecuador', nameAr: 'الإكوادور', flag: '🇪🇨' },
  { code: 'eg', name: 'Egypt', nameAr: 'مصر', flag: '🇪🇬' },
  { code: 'sv', name: 'El Salvador', nameAr: 'السلفادور', flag: '🇸🇻' },
  { code: 'gq', name: 'Equatorial Guinea', nameAr: 'غينيا الاستوائية', flag: '🇬🇶' },
  { code: 'er', name: 'Eritrea', nameAr: 'إريتريا', flag: '🇪🇷' },
  { code: 'ee', name: 'Estonia', nameAr: 'إستونيا', flag: '🇪🇪' },
  { code: 'sz', name: 'Eswatini', nameAr: 'إسواتيني', flag: '🇸🇿' },
  { code: 'et', name: 'Ethiopia', nameAr: 'إثيوبيا', flag: '🇪🇹' },
  { code: 'fj', name: 'Fiji', nameAr: 'فيجي', flag: '🇫🇯' },
  { code: 'fi', name: 'Finland', nameAr: 'فنلندا', flag: '🇫🇮' },
  { code: 'fr', name: 'France', nameAr: 'فرنسا', flag: '🇫🇷' },
  { code: 'ga', name: 'Gabon', nameAr: 'الغابون', flag: '🇬🇦' },
  { code: 'gm', name: 'Gambia', nameAr: 'غامبيا', flag: '🇬🇲' },
  { code: 'ge', name: 'Georgia', nameAr: 'جورجيا', flag: '🇬🇪' },
  { code: 'de', name: 'Germany', nameAr: 'ألمانيا', flag: '🇩🇪' },
  { code: 'gh', name: 'Ghana', nameAr: 'غانا', flag: '🇬🇭' },
  { code: 'gr', name: 'Greece', nameAr: 'اليونان', flag: '🇬🇷' },
  { code: 'gd', name: 'Grenada', nameAr: 'غرينادا', flag: '🇬🇩' },
  { code: 'gt', name: 'Guatemala', nameAr: 'غواتيمالا', flag: '🇬🇹' },
  { code: 'gn', name: 'Guinea', nameAr: 'غينيا', flag: '🇬🇳' },
  { code: 'gw', name: 'Guinea-Bissau', nameAr: 'غينيا بيساو', flag: '🇬🇼' },
  { code: 'gy', name: 'Guyana', nameAr: 'غيانا', flag: '🇬🇾' },
  { code: 'ht', name: 'Haiti', nameAr: 'هايتي', flag: '🇭🇹' },
  { code: 'hn', name: 'Honduras', nameAr: 'هندوراس', flag: '🇭🇳' },
  { code: 'hk', name: 'Hong Kong', nameAr: 'هونغ كونغ', flag: '🇭🇰' },
  { code: 'hu', name: 'Hungary', nameAr: 'المجر', flag: '🇭🇺' },
  { code: 'is', name: 'Iceland', nameAr: 'آيسلندا', flag: '🇮🇸' },
  { code: 'in', name: 'India', nameAr: 'الهند', flag: '🇮🇳' },
  { code: 'id', name: 'Indonesia', nameAr: 'إندونيسيا', flag: '🇮🇩' },
  { code: 'ir', name: 'Iran', nameAr: 'إيران', flag: '🇮🇷' },
  { code: 'iq', name: 'Iraq', nameAr: 'العراق', flag: '🇮🇶' },
  { code: 'ie', name: 'Ireland', nameAr: 'أيرلندا', flag: '🇮🇪' },
  { code: 'il', name: 'Israel', nameAr: 'إسرائيل', flag: '🇮🇱' },
  { code: 'it', name: 'Italy', nameAr: 'إيطاليا', flag: '🇮🇹' },
  { code: 'ci', name: 'Ivory Coast', nameAr: 'ساحل العاج', flag: '🇨🇮' },
  { code: 'jm', name: 'Jamaica', nameAr: 'جامايكا', flag: '🇯🇲' },
  { code: 'jp', name: 'Japan', nameAr: 'اليابان', flag: '🇯🇵' },
  { code: 'jo', name: 'Jordan', nameAr: 'الأردن', flag: '🇯🇴' },
  { code: 'kz', name: 'Kazakhstan', nameAr: 'كازاخستان', flag: '🇰🇿' },
  { code: 'ke', name: 'Kenya', nameAr: 'كينيا', flag: '🇰🇪' },
  { code: 'ki', name: 'Kiribati', nameAr: 'كيريباتي', flag: '🇰🇮' },
  { code: 'kw', name: 'Kuwait', nameAr: 'الكويت', flag: '🇰🇼' },
  { code: 'kg', name: 'Kyrgyzstan', nameAr: 'قيرغيزستان', flag: '🇰🇬' },
  { code: 'la', name: 'Laos', nameAr: 'لاوس', flag: '🇱🇦' },
  { code: 'lv', name: 'Latvia', nameAr: 'لاتفيا', flag: '🇱🇻' },
  { code: 'lb', name: 'Lebanon', nameAr: 'لبنان', flag: '🇱🇧' },
  { code: 'ls', name: 'Lesotho', nameAr: 'ليسوتو', flag: '🇱🇸' },
  { code: 'lr', name: 'Liberia', nameAr: 'ليبيريا', flag: '🇱🇷' },
  { code: 'ly', name: 'Libya', nameAr: 'ليبيا', flag: '🇱🇾' },
  { code: 'li', name: 'Liechtenstein', nameAr: 'ليختنشتاين', flag: '🇱🇮' },
  { code: 'lt', name: 'Lithuania', nameAr: 'ليتوانيا', flag: '🇱🇹' },
  { code: 'lu', name: 'Luxembourg', nameAr: 'لوكسمبورغ', flag: '🇱🇺' },
  { code: 'mo', name: 'Macau', nameAr: 'ماكاو', flag: '🇲🇴' },
  { code: 'mg', name: 'Madagascar', nameAr: 'مدغشقر', flag: '🇲🇬' },
  { code: 'mw', name: 'Malawi', nameAr: 'مالاوي', flag: '🇲🇼' },
  { code: 'my', name: 'Malaysia', nameAr: 'ماليزيا', flag: '🇲🇾' },
  { code: 'mv', name: 'Maldives', nameAr: 'المالديف', flag: '🇲🇻' },
  { code: 'ml', name: 'Mali', nameAr: 'مالي', flag: '🇲🇱' },
  { code: 'mt', name: 'Malta', nameAr: 'مالطا', flag: '🇲🇹' },
  { code: 'mh', name: 'Marshall Islands', nameAr: 'جزر مارشال', flag: '🇲🇭' },
  { code: 'mr', name: 'Mauritania', nameAr: 'موريتانيا', flag: '🇲🇷' },
  { code: 'mu', name: 'Mauritius', nameAr: 'موريشيوس', flag: '🇲🇺' },
  { code: 'mx', name: 'Mexico', nameAr: 'المكسيك', flag: '🇲🇽' },
  { code: 'fm', name: 'Micronesia', nameAr: 'ميكرونيسيا', flag: '🇫🇲' },
  { code: 'md', name: 'Moldova', nameAr: 'مولدوفا', flag: '🇲🇩' },
  { code: 'mc', name: 'Monaco', nameAr: 'موناكو', flag: '🇲🇨' },
  { code: 'mn', name: 'Mongolia', nameAr: 'منغوليا', flag: '🇲🇳' },
  { code: 'me', name: 'Montenegro', nameAr: 'الجبل الأسود', flag: '🇲🇪' },
  { code: 'ma', name: 'Morocco', nameAr: 'المغرب', flag: '🇲🇦' },
  { code: 'mz', name: 'Mozambique', nameAr: 'موزمبيق', flag: '🇲🇿' },
  { code: 'mm', name: 'Myanmar', nameAr: 'ميانمار', flag: '🇲🇲' },
  { code: 'na', name: 'Namibia', nameAr: 'ناميبيا', flag: '🇳🇦' },
  { code: 'nr', name: 'Nauru', nameAr: 'ناورو', flag: '🇳🇷' },
  { code: 'np', name: 'Nepal', nameAr: 'نيبال', flag: '🇳🇵' },
  { code: 'nl', name: 'Netherlands', nameAr: 'هولندا', flag: '🇳🇱' },
  { code: 'nz', name: 'New Zealand', nameAr: 'نيوزيلندا', flag: '🇳🇿' },
  { code: 'ni', name: 'Nicaragua', nameAr: 'نيكاراغوا', flag: '🇳🇮' },
  { code: 'ne', name: 'Niger', nameAr: 'النيجر', flag: '🇳🇪' },
  { code: 'ng', name: 'Nigeria', nameAr: 'نيجيريا', flag: '🇳🇬' },
  { code: 'kp', name: 'North Korea', nameAr: 'كوريا الشمالية', flag: '🇰🇵' },
  { code: 'mk', name: 'North Macedonia', nameAr: 'مقدونيا الشمالية', flag: '🇲🇰' },
  { code: 'no', name: 'Norway', nameAr: 'النرويج', flag: '🇳🇴' },
  { code: 'om', name: 'Oman', nameAr: 'عمان', flag: '🇴🇲' },
  { code: 'pk', name: 'Pakistan', nameAr: 'باكستان', flag: '🇵🇰' },
  { code: 'pw', name: 'Palau', nameAr: 'بالاو', flag: '🇵🇼' },
  { code: 'ps', name: 'Palestine', nameAr: 'فلسطين', flag: '🇵🇸' },
  { code: 'pa', name: 'Panama', nameAr: 'بنما', flag: '🇵🇦' },
  { code: 'pg', name: 'Papua New Guinea', nameAr: 'بابوا غينيا الجديدة', flag: '🇵🇬' },
  { code: 'py', name: 'Paraguay', nameAr: 'باراغواي', flag: '🇵🇾' },
  { code: 'pe', name: 'Peru', nameAr: 'بيرو', flag: '🇵🇪' },
  { code: 'ph', name: 'Philippines', nameAr: 'الفلبين', flag: '🇵🇭' },
  { code: 'pl', name: 'Poland', nameAr: 'بولندا', flag: '🇵🇱' },
  { code: 'pt', name: 'Portugal', nameAr: 'البرتغال', flag: '🇵🇹' },
  { code: 'qa', name: 'Qatar', nameAr: 'قطر', flag: '🇶🇦' },
  { code: 'ro', name: 'Romania', nameAr: 'رومانيا', flag: '🇷🇴' },
  { code: 'ru', name: 'Russia', nameAr: 'روسيا', flag: '🇷🇺' },
  { code: 'rw', name: 'Rwanda', nameAr: 'رواندا', flag: '🇷🇼' },
  { code: 'kn', name: 'Saint Kitts and Nevis', nameAr: 'سانت كيتس ونيفيس', flag: '🇰🇳' },
  { code: 'lc', name: 'Saint Lucia', nameAr: 'سانت لوسيا', flag: '🇱🇨' },
  { code: 'vc', name: 'Saint Vincent and the Grenadines', nameAr: 'سانت فنسنت والغرينادين', flag: '🇻🇨' },
  { code: 'ws', name: 'Samoa', nameAr: 'ساموا', flag: '🇼🇸' },
  { code: 'sm', name: 'San Marino', nameAr: 'سان مارينو', flag: '🇸🇲' },
  { code: 'st', name: 'Sao Tome and Principe', nameAr: 'ساو تومي وبرينسيبي', flag: '🇸🇹' },
  { code: 'sa', name: 'Saudi Arabia', nameAr: 'المملكة العربية السعودية', flag: '🇸🇦' },
  { code: 'sn', name: 'Senegal', nameAr: 'السنغال', flag: '🇸🇳' },
  { code: 'rs', name: 'Serbia', nameAr: 'صربيا', flag: '🇷🇸' },
  { code: 'sc', name: 'Seychelles', nameAr: 'سيشل', flag: '🇸🇨' },
  { code: 'sl', name: 'Sierra Leone', nameAr: 'سيراليون', flag: '🇸🇱' },
  { code: 'sg', name: 'Singapore', nameAr: 'سنغافورة', flag: '🇸🇬' },
  { code: 'sk', name: 'Slovakia', nameAr: 'سلوفاكيا', flag: '🇸🇰' },
  { code: 'si', name: 'Slovenia', nameAr: 'سلوفينيا', flag: '🇸🇮' },
  { code: 'sb', name: 'Solomon Islands', nameAr: 'جزر سليمان', flag: '🇸🇧' },
  { code: 'so', name: 'Somalia', nameAr: 'الصومال', flag: '🇸🇴' },
  { code: 'za', name: 'South Africa', nameAr: 'جنوب أفريقيا', flag: '🇿🇦' },
  { code: 'kr', name: 'South Korea', nameAr: 'كوريا الجنوبية', flag: '🇰🇷' },
  { code: 'ss', name: 'South Sudan', nameAr: 'جنوب السودان', flag: '🇸🇸' },
  { code: 'es', name: 'Spain', nameAr: 'إسبانيا', flag: '🇪🇸' },
  { code: 'lk', name: 'Sri Lanka', nameAr: 'سريلانكا', flag: '🇱🇰' },
  { code: 'sd', name: 'Sudan', nameAr: 'السودان', flag: '🇸🇩' },
  { code: 'sr', name: 'Suriname', nameAr: 'سورينام', flag: '🇸🇷' },
  { code: 'se', name: 'Sweden', nameAr: 'السويد', flag: '🇸🇪' },
  { code: 'ch', name: 'Switzerland', nameAr: 'سويسرا', flag: '🇨🇭' },
  { code: 'sy', name: 'Syria', nameAr: 'سوريا', flag: '🇸🇾' },
  { code: 'tw', name: 'Taiwan', nameAr: 'تايوان', flag: '🇹🇼' },
  { code: 'tj', name: 'Tajikistan', nameAr: 'طاجيكستان', flag: '🇹🇯' },
  { code: 'tz', name: 'Tanzania', nameAr: 'تنزانيا', flag: '🇹🇿' },
  { code: 'th', name: 'Thailand', nameAr: 'تايلاند', flag: '🇹🇭' },
  { code: 'tl', name: 'Timor-Leste', nameAr: 'تيمور الشرقية', flag: '🇹🇱' },
  { code: 'tg', name: 'Togo', nameAr: 'توغو', flag: '🇹🇬' },
  { code: 'to', name: 'Tonga', nameAr: 'تونغا', flag: '🇹🇴' },
  { code: 'tt', name: 'Trinidad and Tobago', nameAr: 'ترينيداد وتوباغو', flag: '🇹🇹' },
  { code: 'tn', name: 'Tunisia', nameAr: 'تونس', flag: '🇹🇳' },
  { code: 'tr', name: 'Turkey', nameAr: 'تركيا', flag: '🇹🇷' },
  { code: 'tm', name: 'Turkmenistan', nameAr: 'تركمانستان', flag: '🇹🇲' },
  { code: 'tv', name: 'Tuvalu', nameAr: 'توفالو', flag: '🇹🇻' },
  { code: 'ug', name: 'Uganda', nameAr: 'أوغندا', flag: '🇺🇬' },
  { code: 'ua', name: 'Ukraine', nameAr: 'أوكرانيا', flag: '🇺🇦' },
  { code: 'ae', name: 'United Arab Emirates', nameAr: 'الإمارات العربية المتحدة', flag: '🇦🇪' },
  { code: 'gb', name: 'United Kingdom', nameAr: 'المملكة المتحدة', flag: '🇬🇧' },
  { code: 'us', name: 'United States', nameAr: 'الولايات المتحدة', flag: '🇺🇸' },
  { code: 'uy', name: 'Uruguay', nameAr: 'أوروغواي', flag: '🇺🇾' },
  { code: 'uz', name: 'Uzbekistan', nameAr: 'أوزبكستان', flag: '🇺🇿' },
  { code: 'vu', name: 'Vanuatu', nameAr: 'فانواتو', flag: '🇻🇺' },
  { code: 'va', name: 'Vatican City', nameAr: 'الفاتيكان', flag: '🇻🇦' },
  { code: 've', name: 'Venezuela', nameAr: 'فنزويلا', flag: '🇻🇪' },
  { code: 'vn', name: 'Vietnam', nameAr: 'فيتنام', flag: '🇻🇳' },
  { code: 'ye', name: 'Yemen', nameAr: 'اليمن', flag: '🇾🇪' },
  { code: 'zm', name: 'Zambia', nameAr: 'زامبيا', flag: '🇿🇲' },
  { code: 'zw', name: 'Zimbabwe', nameAr: 'زيمبابوي', flag: '🇿🇼' },
];

// Helper function to get country by code
export function getCountryByCode(code: string): Country | undefined {
  return COUNTRIES.find((c) => c.code === code.toLowerCase());
}

// Helper function to search countries
export function searchCountries(query: string): Country[] {
  const lowerQuery = query.toLowerCase();
  return COUNTRIES.filter(
    (c) =>
      c.name.toLowerCase().includes(lowerQuery) ||
      c.nameAr.includes(query) ||
      c.code.includes(lowerQuery)
  );
}

// Popular countries for quick access (used in filters)
export const POPULAR_COUNTRIES = COUNTRIES.filter((c) =>
  ['tr', 'us', 'gb', 'ca', 'de', 'au', 'jp', 'fr', 'nl', 'ch', 'se', 'my', 'sa', 'ae', 'qa'].includes(c.code)
);
