import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// University Admissions Seed Data
const admissionsData = [
  // ============ BACHELOR PROGRAMS ============
  {
    universityNameEn: 'Istanbul University',
    universityNameTr: 'İstanbul Üniversitesi',
    universityNameAr: 'جامعة اسطنبول',
    city: 'Istanbul',
    cityAr: 'اسطنبول',
    degree: 'bachelor',
    registrationStart: new Date('2026-01-15'),
    registrationEnd: new Date('2026-02-28'),
    resultsDate: new Date('2026-03-15'),
    acceptedCertificates: ['TR-YOS', 'SAT'],
    detailsUrl: 'https://www.istanbul.edu.tr',
    applicationType: 'yos',
    localRanking: 1,
    isFreeApplication: true,
    calendarType: 'bachelor',
    languageOfInstruction: ['Turkish', 'English'],
  },
  {
    universityNameEn: 'Bogazici University',
    universityNameTr: 'Boğaziçi Üniversitesi',
    universityNameAr: 'جامعة البوسفور',
    city: 'Istanbul',
    cityAr: 'اسطنبول',
    degree: 'bachelor',
    registrationStart: new Date('2026-02-01'),
    registrationEnd: new Date('2026-03-15'),
    resultsDate: new Date('2026-04-01'),
    acceptedCertificates: ['SAT', 'ACT', 'IB', 'GCE', 'ABITUR'],
    detailsUrl: 'https://www.boun.edu.tr',
    applicationType: 'sat',
    localRanking: 1,
    isFreeApplication: false,
    applicationFee: 75,
    applicationFeeCurrency: 'USD',
    calendarType: 'bachelor',
    languageOfInstruction: ['English'],
  },
  {
    universityNameEn: 'Hacettepe University',
    universityNameTr: 'Hacettepe Üniversitesi',
    universityNameAr: 'جامعة حجي تبه',
    city: 'Ankara',
    cityAr: 'أنقرة',
    degree: 'bachelor',
    specialization: 'Medicine & Health Sciences',
    registrationStart: new Date('2026-01-25'),
    registrationEnd: new Date('2026-02-28'),
    resultsDate: new Date('2026-03-15'),
    acceptedCertificates: ['TR-YOS', 'TYOS', 'SAT', 'THANAWEYA_SD', 'THANAWEYA'],
    detailsUrl: 'https://www.hacettepe.edu.tr',
    applicationType: 'yos',
    localRanking: 3,
    isFreeApplication: false,
    applicationFee: 200,
    applicationFeeCurrency: 'TRY',
    calendarType: 'bachelor',
    languageOfInstruction: ['Turkish', 'English'],
  },
  {
    universityNameEn: 'Bilkent University',
    universityNameTr: 'Bilkent Üniversitesi',
    universityNameAr: 'جامعة بيلكنت',
    city: 'Ankara',
    cityAr: 'أنقرة',
    degree: 'bachelor',
    registrationStart: new Date('2026-01-15'),
    registrationEnd: new Date('2026-02-20'),
    resultsDate: new Date('2026-03-05'),
    acceptedCertificates: ['SAT', 'ACT', 'IB', 'AP', 'GCE'],
    detailsUrl: 'https://www.bilkent.edu.tr',
    applicationType: 'sat',
    localRanking: 4,
    isFreeApplication: false,
    applicationFee: 50,
    applicationFeeCurrency: 'USD',
    calendarType: 'bachelor',
    languageOfInstruction: ['English'],
  },
  {
    universityNameEn: 'Ankara University',
    universityNameTr: 'Ankara Üniversitesi',
    universityNameAr: 'جامعة أنقرة',
    city: 'Ankara',
    cityAr: 'أنقرة',
    degree: 'bachelor',
    registrationStart: new Date('2026-01-20'),
    registrationEnd: new Date('2026-03-10'),
    resultsDate: new Date('2026-03-25'),
    acceptedCertificates: ['TR-YOS', 'AYOS', 'SAT', 'THANAWEYA_SD', 'THANAWEYA_SY', 'THANAWEYA_EG'],
    detailsUrl: 'https://www.ankara.edu.tr',
    applicationType: 'yos',
    localRanking: 5,
    isFreeApplication: true,
    calendarType: 'bachelor',
    languageOfInstruction: ['Turkish', 'English'],
  },
  {
    universityNameEn: 'Ege University',
    universityNameTr: 'Ege Üniversitesi',
    universityNameAr: 'جامعة إيجه',
    city: 'Izmir',
    cityAr: 'إزمير',
    degree: 'bachelor',
    registrationStart: new Date('2026-02-10'),
    registrationEnd: new Date('2026-03-20'),
    resultsDate: new Date('2026-04-05'),
    acceptedCertificates: ['TR-YOS', 'AYOS', 'UNIYOS', 'THANAWEYA_SD', 'THANAWEYA_SY'],
    detailsUrl: 'https://www.ege.edu.tr',
    applicationType: 'yos',
    localRanking: 8,
    isFreeApplication: true,
    calendarType: 'bachelor',
    languageOfInstruction: ['Turkish'],
  },
  {
    universityNameEn: 'Dokuz Eylul University',
    universityNameTr: 'Dokuz Eylül Üniversitesi',
    universityNameAr: 'جامعة دوكوز أيلول',
    city: 'Izmir',
    cityAr: 'إزمير',
    degree: 'bachelor',
    registrationStart: new Date('2026-02-15'),
    registrationEnd: new Date('2026-03-25'),
    resultsDate: new Date('2026-04-10'),
    acceptedCertificates: ['TR-YOS', 'THANAWEYA_SD', 'THANAWEYA_EG', 'THANAWEYA_JO'],
    detailsUrl: 'https://www.deu.edu.tr',
    applicationType: 'direct',
    localRanking: 12,
    isFreeApplication: true,
    calendarType: 'bachelor',
    languageOfInstruction: ['Turkish'],
  },

  // ============ MASTERS & PHD PROGRAMS ============
  {
    universityNameEn: 'Middle East Technical University - PhD Programs',
    universityNameTr: 'Orta Doğu Teknik Üniversitesi - Doktora Programları',
    universityNameAr: 'جامعة الشرق الأوسط التقنية - برامج الدكتوراه',
    city: 'Ankara',
    cityAr: 'أنقرة',
    degree: 'phd',
    specialization: 'Engineering & Sciences',
    registrationStart: new Date('2026-02-01'),
    registrationEnd: new Date('2026-03-31'),
    resultsDate: new Date('2026-04-20'),
    acceptedCertificates: ['ALES', 'GRE', 'GRE_SUBJECT', 'YDS', 'TOEFL', 'IELTS', 'MASTER_DEGREE', 'TRANSCRIPT'],
    detailsUrl: 'https://fbe.metu.edu.tr',
    applicationType: 'ales-based',
    localRanking: 2,
    isFreeApplication: false,
    applicationFee: 150,
    applicationFeeCurrency: 'TRY',
    calendarType: 'masters-phd',
    languageOfInstruction: ['English'],
  },
  {
    universityNameEn: 'Ankara University - Graduate School',
    universityNameTr: 'Ankara Üniversitesi - Lisansüstü',
    universityNameAr: 'جامعة أنقرة - الدراسات العليا',
    city: 'Ankara',
    cityAr: 'أنقرة',
    degree: 'master',
    registrationStart: new Date('2026-02-01'),
    registrationEnd: new Date('2026-03-15'),
    resultsDate: new Date('2026-04-01'),
    acceptedCertificates: ['ALES', 'GRE'],
    detailsUrl: 'https://www.ankara.edu.tr',
    applicationType: 'direct',
    localRanking: 5,
    isFreeApplication: false,
    applicationFee: 100,
    applicationFeeCurrency: 'TRY',
    calendarType: 'masters-phd',
    languageOfInstruction: ['Turkish', 'English'],
  },
  {
    universityNameEn: 'Karadeniz Technical University - Graduate School',
    universityNameTr: 'Karadeniz Teknik Üniversitesi - Lisansüstü',
    universityNameAr: 'جامعة كارادينيز التقنية - الدراسات العليا',
    city: 'Trabzon',
    cityAr: 'طرابزون',
    degree: 'master',
    specialization: 'Engineering Programs',
    registrationStart: new Date('2026-01-15'),
    registrationEnd: new Date('2026-02-28'),
    resultsDate: new Date('2026-03-20'),
    acceptedCertificates: ['ALES', 'YDS', 'YOKDIL', 'TOEFL', 'IELTS', 'BACHELOR_DEGREE', 'TRANSCRIPT'],
    detailsUrl: 'https://fbe.ktu.edu.tr',
    applicationType: 'graduate-institute',
    localRanking: 15,
    isFreeApplication: true,
    calendarType: 'masters-phd',
    languageOfInstruction: ['Turkish', 'English'],
  },

  // ============ SUMMER PROGRAMS ============
  {
    universityNameEn: 'Istanbul University - Summer School',
    universityNameTr: 'İstanbul Üniversitesi - Yaz Okulu',
    universityNameAr: 'جامعة اسطنبول - المدرسة الصيفية',
    city: 'Istanbul',
    cityAr: 'اسطنبول',
    degree: 'all',
    specialization: 'Turkish Language & Culture',
    registrationStart: new Date('2026-04-01'),
    registrationEnd: new Date('2026-05-31'),
    resultsDate: new Date('2026-06-15'),
    acceptedCertificates: ['TOEFL', 'IELTS', 'DUOLINGO', 'TOMER'],
    detailsUrl: 'https://yazokullar.istanbul.edu.tr',
    applicationType: 'online-portal',
    localRanking: 1,
    isFreeApplication: false,
    applicationFee: 200,
    applicationFeeCurrency: 'USD',
    calendarType: 'summer',
    programDuration: '6-weeks',
    languageOfInstruction: ['Turkish', 'English'],
  },
  {
    universityNameEn: 'Bogazici University Summer School',
    universityNameTr: 'Boğaziçi Üniversitesi Yaz Okulu',
    universityNameAr: 'جامعة بوغازيتشي - البرنامج الصيفي',
    city: 'Istanbul',
    cityAr: 'اسطنبول',
    degree: 'all',
    registrationStart: new Date('2026-04-01'),
    registrationEnd: new Date('2026-05-15'),
    resultsDate: new Date('2026-05-20'),
    acceptedCertificates: ['TOEFL', 'IELTS', 'DUOLINGO'],
    detailsUrl: 'https://www.boun.edu.tr/summer',
    applicationType: 'direct',
    localRanking: 2,
    isFreeApplication: false,
    applicationFee: 500,
    applicationFeeCurrency: 'USD',
    calendarType: 'summer',
    programDuration: '8-weeks',
    languageOfInstruction: ['English'],
  },
];

async function seedAdmissions() {
  console.log('Seeding university admissions...');

  // Clear existing admissions
  await prisma.universityAdmission.deleteMany();
  console.log('Cleared existing admissions');

  // Insert new admissions
  for (const admission of admissionsData) {
    const created = await prisma.universityAdmission.create({
      data: admission as any,
    });
    console.log(`Created: ${created.universityNameEn} (${created.calendarType})`);
  }

  console.log(`\nSeeded ${admissionsData.length} university admissions:`);
  console.log(`  - Bachelor: ${admissionsData.filter(a => a.calendarType === 'bachelor').length}`);
  console.log(`  - Masters/PhD: ${admissionsData.filter(a => a.calendarType === 'masters-phd').length}`);
  console.log(`  - Summer: ${admissionsData.filter(a => a.calendarType === 'summer').length}`);
}

seedAdmissions()
  .catch((e) => {
    console.error('Error seeding admissions:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
